# whitelist
branches:
  only:
    - wporg

language: php

php:
  - 5.2
  - 5.3

sudo: false

addons:
  apt:
    packages:
    - ruby


install: gem install nyx

cache: bundler

script:
    - nyx version
    - nyx check:php .

notifications:
  email:
    recipients:
    - andrei.lupu@pixelgrade.com
    on_failure: always
