# whitelist
branches:
  only:
    - wporg

language: php

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6

sudo: false

addons:
  apt:
    packages:
    - ruby


install: gem install nyx

cache: bundler

script:
    - nyx check:php .